name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Updated to v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0  # Updated to v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add SSH key scan
        run: |
          ssh-keyscan 185.201.9.128 >> ~/.ssh/known_hosts

      - name: Test SSH Connection
        run: |
          ssh -o StrictHostKeyChecking=no root@185.201.9.128 'echo "SSH connection successful"'

      - name: Deploy to VPS
        run: |
          ssh -o StrictHostKeyChecking=no root@185.201.9.128 '
          cd /var/www/567plus-id &&
          git stash &&
          git pull origin main &&
          npm install &&
          npm run build &&
          pm2 restart 567plus-id
          '
